// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClientEmailAPI.Data.Models
{
    public partial class TblMobileEmail
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string Phonenumber { get; set; }
        public string Passcode { get; set; }
        public string Host { get; set; }
        public int? Ssl { get; set; }
        public int? Port { get; set; }
    }
}