// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClientEmailAPI.Data.Models
{
    public partial class TblWebEmail
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string Phonenumber { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public bool Ssl { get; set; }
        public int? Port { get; set; }
    }
}